Models/Reserva.cs
using Microsoft.DotNet.Scaffolding.Shared.CodeModifier.CodeChange;
using ShoraWebsite.Models;
using System.ComponentModel.DataAnnotations;

namespace ShoraWebsite.Models
{


    public class Reserva
    {
        [Key]
        public int Id { get; set; }

        public int RoupaId { get; set; }

        public Roupa? Roupa { get; set; }

        public int PerfilId { get; set; }

        public Perfil? Perfil { get; set; }

        public int Quantidade { get; set; }

        public string? Tamanho { get; set; } 

        public bool Vendida { get; set; } = false;

        public MetodoDeEnvio Envio { get; set; } = MetodoDeEnvio.Nenhum;

    }
}

Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoraWebsite.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ShoraWebsite.Models;
using ShoraWebsite.Data.Migrations;

namespace ShoraWebsite.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public AccountsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        [Authorize(Roles = "Admin")]
        public IActionResult AdminPainel()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {

            var users = _userManager.Users;
            var model = new List<UsersRolesViewModel>();
            foreach (var user in users)
            {
                var roles = _userManager.GetRolesAsync(user).Result;
                model.Add(new UsersRolesViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    Role = roles.SingleOrDefault()
                });
            }
            return View(model);
        }


        [Authorize(Roles = "Admin,Cliente")]
        public IActionResult Chat(int? id)
        {


            if (!ReservaExiste(id))
            {
                return RedirectToAction("Index", "Home");
            }

            var reserva = _context.Reserva
                .Include(x => x.Roupa)
                .Include(x => x.Perfil)
                .Include(x => x.Perfil.User)
                .SingleOrDefault(x => x.Id == id);
            if (reserva.Perfil.User.UserName == User.Identity.Name || User.IsInRole("Admin"))
            {
                ViewData["MetodoId"] = new SelectList(ReservasController.GetMetodoDeEnvio(), "value", "metodo", reserva.Envio);
                ViewBag.Id = id;
                return View(reserva);
            }

            return RedirectToAction("Index", "Home");

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Editar(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var roles = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();

            var model = new UsersRolesViewModel
            {
                Id = user.Id,
                Email = user.Email,
                Role = (await _userManager.GetRolesAsync(user)).SingleOrDefault(),
                Roles = roles
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(string id, UsersRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var oldRole = model.Role;
            // Remove o user de todos os roles
            var result = await _userManager.RemoveFromRolesAsync(user, await _userManager.GetRolesAsync(user));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("Role", "Um erro ococrreu a dar update ao role do utilizador.");
                model.Role = oldRole;
                return View(model);
            }

            // Adicionar o role selecionado ao utilizador
            result = await _userManager.AddToRoleAsync(user, model.Role);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("Role", "Um erro ococrreu a dar update ao role do utilizador.");
                model.Role = oldRole;

                return View(model);
            }

            return RedirectToAction("Index");
        }


        public bool ReservaExiste(int? id)
        {
            if (id == null)
            {
                return false;
            }
            return _context.Reserva.Any(x => x.Id == id);
        }

    }
}

Controllers/ReservasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoraWebsite.Data;
using ShoraWebsite.Models;
using System.Collections;
using System.Data;

namespace ShoraWebsite.Controllers
{
    public class ReservasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ReservasController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        //Get
        [Authorize(Roles = "Cliente")]
        public async Task<IActionResult> MinhasReservas()
        {
            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;

            List<MyReservationsViewModel> models = new List<MyReservationsViewModel>();
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var reservas = await _context.Reserva
                .Where(r => r.Perfil.UserId == user.Id)
           .Include(r => r.Perfil)
           .Include(r => r.Roupa)
           .ToListAsync();

            foreach (var reserva in reservas)
            {
                models.Add(new MyReservationsViewModel()
                {
                    Reserva = reserva,
                    UnreadMessages = _context.Messages.Where(x => x.ReservaId == reserva.Id).Count(x => x.IsVistaCliente == false)
                });
            }

            return View(models);

        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Order(string value)
        {

            if (_context.Reserva == null)
            {
                return NotFound();
            }

            ViewBag.Value = value;

            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;

            //0 é ascending - 1 é descending
            switch (value)
            {
                case "0"://Não Vendido
                    return View(await _context.Reserva
               .Include(r => r.Perfil)
               .Include(r => r.Roupa)
               .Where(r => r.Vendida == false)
               .ToListAsync());

                case "1"://Vendido
                    return View(await _context.Reserva
              .Include(r => r.Perfil)
              .Include(r => r.Roupa)
              .Where(r => r.Vendida == true)
              .ToListAsync());

                default:

                    return RedirectToAction(nameof(Listagem));

            }


        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Listagem()
        {


            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;

            List<MyReservationsViewModel> models = new List<MyReservationsViewModel>();
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var reservas = await _context.Reserva
                .Include(r => r.Perfil)
                .Include(r => r.Roupa)
                .ToListAsync();

            foreach (var reserva in reservas)
            {
                models.Add(new MyReservationsViewModel()
                {
                    Reserva = reserva,
                    UnreadMessages = _context.Messages.Where(x => x.ReservaId == reserva.Id).Count(x => x.IsVistaAdmin == false)
                });
            }

            return View(models);

        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Listagem(IFormCollection formData)
        {
            string search = formData["search"];

            MetodoDeEnvio[] values = (MetodoDeEnvio[])Enum.GetValues(typeof(MetodoDeEnvio));

            var list = await _context.Reserva
                  .Where(r => r.Perfil.FirstName.Contains(search) || r.Perfil.LastName.Contains(search) || r.Roupa.Name.Contains(search) || r.Tamanho.Contains(search))
            .Include(r => r.Perfil)
            .Include(r => r.Roupa)
            .ToListAsync();

            foreach (var metodo in values)
            {
                if (metodo.ToString().Contains(search))
                {
                    var listComMetodo = _context.Reserva
                        .Include(x => x.Roupa)
                        .Include(x => x.Perfil)
                        .Where(x => x.Envio == metodo);

                    foreach (var r in listComMetodo)
                    {
                        if (!list.Contains(r))
                        {
                            list.Add(r);
                        }
                    }
                }
            }

            return View(list);
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SwitchVendida(int id, [Bind("Id,RoupaId,PerfilId,Quantidade,Tamanho,Vendida")] Reserva reserva)
        {
            //Lista de mensagens de Erro e de Status
            List<string>? errorsMessages = new List<string>();
            List<string>? statusMessages = new List<string>();

            if (id != reserva.Id || reserva == null || !_context.Roupa.Any(r => r.Id == reserva.RoupaId) || !_context.Reserva.Any(r => r.Id == reserva.Id))
            {

                return NotFound();
            }


            try
            {
                var roupa = _context.Roupa.Find(reserva.RoupaId);
                reserva = _context.Reserva.Find(id);

                reserva.Vendida = !reserva.Vendida;
                _context.Update(reserva);
                await _context.SaveChangesAsync();

                statusMessages.Add($"A venda do material {roupa.Name} - {reserva.Tamanho} foi colocado como {reserva.Vendida}");
            }
            catch (Exception)
            {
                errorsMessages.Add($"Houve um erro a guardar a alteração ");
            }

            if (errorsMessages.Count == 0)
            {
                errorsMessages = null;
            }

            if (statusMessages.Count == 0)
            {
                statusMessages = null;
            }

            TempData["errorsMessages"] = errorsMessages;
            TempData["statusMessages"] = statusMessages;



            return RedirectToAction(nameof(Listagem));
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {

            //Lista de mensagens de Erro e de Status
            List<string>? errorsMessages = new List<string>();
            List<string>? statusMessages = new List<string>();

            if (_context.Reserva == null)
            {
                errorsMessages.Add($"Não foi encontrada nenhuma reserva na Base de Dados");
            }
            if (!_context.Reserva.Any(r => r.Id == id))
            {
                errorsMessages.Add($"Não foi encontrada nenhuma reserva com esse id {id} na Base de Dados");

            }

            var reserva = await _context.Reserva.FindAsync(id);


            //Adiciono de novo o stock
            if (_context.StockMaterial != null && _context.StockMaterial.Any(s => s.RoupaId == reserva.RoupaId && s.Tamanho == reserva.Tamanho))
            {
                var stock = _context.StockMaterial.FirstOrDefault(s => s.RoupaId == reserva.RoupaId && s.Tamanho == reserva.Tamanho);
                stock.Quantidade += reserva.Quantidade;
                _context.Update(stock);

            }
            else
            {
                _context.StockMaterial.Add(new Models.Stock()
                {
                    Quantidade = reserva.Quantidade,
                    RoupaId = reserva.RoupaId,
                    Tamanho = reserva.Tamanho
                });
            }


            _context.Reserva.Remove(reserva);
            await _context.SaveChangesAsync();

            statusMessages.Add($"Foi removido com sucesso a reserva {reserva.Roupa}-{reserva.Tamanho} com {reserva.Quantidade}");


            return RedirectToAction(nameof(Listagem));
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null || _context.Reserva == null)
            {
                return NotFound();
            }

            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;


            var reserva = await _context.Reserva.FindAsync(id);

            if (reserva == null)
            {
                return NotFound();
            }
            ViewData["MetodoId"] = new SelectList(GetMetodoDeEnvio(), "value", "metodo", reserva.Envio);

            return View(reserva);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Editar(int id, [Bind("Id,RoupaId,PerfilId,Quantidade,Tamanho,Envio,Vendida")] Reserva reserva, IFormCollection formData)
        {
            //Lista de erros e de status
            List<string> errorMessages = new List<string>();
            List<string> statusMessages = new List<string>();

Views/Reservas/Editar.cshtml
@model ShoraWebsite.Models.Reserva


@if (ViewBag.statusMessages != null)
{
    <div class="alert alert-success alert-dismissible" role="alert" id="statusMessage">
        @foreach (var s in ViewBag.statusMessages)
        {
            <p>@s</p>
        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('statusMessage')"></button>
    </div>
}


@if (ViewBag.errorsMessages != null)
{
    <div class="alert alert-danger alert-dismissible " role="alert" id="errorMessage">
        @foreach (var s in ViewBag.errorsMessages)
        {
            <p>@s</p>

        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('errorMessage')"></button>
    </div>
}

<h4>Alterar a Reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4 pad">
        <form asp-action="Editar" asp-controller="Reservas">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="PerfilId" />
            <input type="hidden" asp-for="Vendida" />
            <input type="hidden" asp-for="RoupaId" />
            <input type="hidden" asp-for="Tamanho" />

            <input type ="hidden" name="OldQuant" value="@Model.Quantidade" />



            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
             <div class="form-group">
                Metodo de Envio
                <select asp-for="Envio" class="form-control" asp-items="ViewBag.MetodoId"></select>
                <span asp-validation-for="Envio" class="text-danger"></span>
            </div>
            <div class="form-group pad">
                <input type="submit" value="Guardar Alteração" class="botaoDanger nav-link" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Listagem" asp-controller="Reservas" class="botao nav-link">Voltar a lista de Reservas </a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Reservas/Listagem.cshtml
@model IEnumerable<ShoraWebsite.Models.MyReservationsViewModel>


@if (ViewBag.statusMessages != null)
{
    <div class="alert alert-success alert-dismissible" role="alert" id="statusMessage">
        @foreach (var s in ViewBag.statusMessages)
        {
            <p>@s</p>
        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('statusMessage')"></button>
    </div>
}


@if (ViewBag.errorsMessages != null)
{
    <div class="alert alert-danger alert-dismissible " role="alert" id="errorMessage">
        @foreach (var s in ViewBag.errorsMessages)
        {
            <p>@s</p>

        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('errorMessage')"></button>
    </div>
}


<div class="container">
    <div class="row">
        <form asp-action="Listagem">
            <div class="input-group rounded">
                <input type="search" name="search" class="form-control rounded" placeholder="Pesquisa" aria-label="Search" aria-describedby="search-addon" />

                <button type="submit" class="btn btn-outline-dark">
                    <img src="/Documentos/Icons/searchIcon.png" height="30" width="30" />
                </button>

            </div>
        </form>
    </div>
    <div class="row">
        <h2> Lista de Reservas </h2>
    </div>
    <div class="row">

        <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                Ordenar
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li> <a class="nav-link text-dark" asp-action="Listagem"> Tudo </a></li>
                <li> <a class="nav-link text-dark" asp-route="ordered" asp-route-value="0">Não Vendido</a></li>
                <li><a class="nav-link text-dark" asp-route="ordered" asp-route-value="1"> Vendido</a></li>
            </ul>
        </div>

    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-sm">
            <partial name="Listing" model="@Model" />
        </div>


    </div>
</div>

Views/Reservas/Listing.cshtml
@model IEnumerable<ShoraWebsite.Models.MyReservationsViewModel>



@if (Model.Any(r => r.Reserva.Vendida == true))
{
    float lucro = 0;
    foreach (var r in Model)
    {
        if (r.Reserva.Vendida == true && r.Reserva.Roupa != null)
        {
            var temp = r.Reserva.Quantidade * r.Reserva.Roupa.Preco;
            lucro += temp;
        }
    }
    <p>Lucro : @lucro </p>

}

<table class="table">
    <thead>
        <tr>
            <th>
                Nome do Comprador
            </th>

            <th>
                Nome do Material
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reserva.Quantidade)
            </th>
            <th>Tamanho</th>

            <th>
                @Html.DisplayNameFor(model => model.Reserva.Envio)
            </th>

            <th>Vendida/Reservada</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Perfil.FirstName) @Html.DisplayFor(modelItem => item.Reserva.Perfil.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Roupa.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Quantidade)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Tamanho)
                </td>

                <th>
                    @item.Reserva.Envio
                </th>

                <td>
                    <form method="post" asp-action="SwitchVendida" asp-route-id="@item.Reserva.Id">
                        <input type="hidden" name="reserva.Id" value="@item.Reserva.Id" />
                        <input type="hidden" name="reserva.RoupaId" value="@item.Reserva.RoupaId" />
                        <input type="hidden" name="reserva.PerfilId" value="@item.Reserva.PerfilId" />
                        <input type="hidden" name="reserva.Quantidade" value="@item.Reserva.Quantidade" />
                        <input type="hidden" name="reserva.Tamanho" value="@item.Reserva.Tamanho" />
                        <input type="hidden" name="reserva.Vendida" value="@item.Reserva.Vendida" />

                        <button type="submit" class="btn" onclick="return confirm('De certeza que queres trocar o status de @item.Reserva.Roupa.Name do user @item.Reserva.Perfil.FirstName @item.Reserva.Perfil.LastName?')">
                            @if (item.Reserva.Vendida)
                            {
                                 <img src="/Documentos/Icons/switchOnBox.png" height="30" width="30" />

                            }
                            else{
                                 <img src="/Documentos/Icons/switchOffBox.png" height="30" width="30" />

                                }

                        </button>
                    </form>
                </td>
                <td>
                    <a asp-action="Chat" asp-controller="Accounts" asp-route-id="@item.Reserva.Id">
                        <img src="~/documentos/icons/chaticon.png" height="30" width="30"/>
                    </a>
                    @if (item.UnreadMessages>0)
                    {
                        <strong class="noUnderline" style="color:red;">@item.UnreadMessages</strong>

                    }
                </td>
                <td>

                    <a asp-action="Editar" asp-route-id="@item.Reserva.Id">
                        <img src="/Documentos/Icons/edit.png" height="30" width="30" />
                    </a>
                    
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Reserva.Id" onclick="return confirm('De certeza que queres apagar a reserva de @item.Reserva.Roupa.Name - @item.Reserva.Tamanho pertecente  a @item.Reserva.Perfil.FirstName @item.Reserva.Perfil.LastName ?')">
                        <img src="/Documentos/Icons/delete.png" height="30" width="30" />
                    </a>

                </td>
            </tr>

        }

    </tbody>

</table>

Views/Reservas/MinhasReservas.cshtml
@model IEnumerable<ShoraWebsite.Models.MyReservationsViewModel>


@if (ViewBag.statusMessages != null)
{
    <div class="alert alert-success alert-dismissible" role="alert" id="statusMessage">
        @foreach (var s in ViewBag.statusMessages)
        {
            <p>@s</p>
        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('statusMessage')"></button>
    </div>
}


@if (ViewBag.errorsMessages != null)
{
    <div class="alert alert-danger alert-dismissible " role="alert" id="errorMessage">
        @foreach (var s in ViewBag.errorsMessages)
        {
            <p>@s</p>

        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('errorMessage')"></button>
    </div>
}


<div class="container">
    <div class="row">
        <h2> Minhas Reservas </h2>
    </div>
    

    <!-- COLOCAR AQUI UMA IMAGAEM ?? -->
</div>


<div class="container">
    <div class="row">
        <div class="col-sm">
            <partial name="MyListing" model="@Model" />
        </div>


    </div>
</div>

Views/Reservas/MyListing.cshtml
@model IEnumerable<ShoraWebsite.Models.MyReservationsViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                Nome do Material
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Reserva.Quantidade)
            </th>
            <th>Tamanho</th>

            <th>
                @Html.DisplayNameFor(model => model.Reserva.Envio)
            </th>
            <th> Entrar em Contacto</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Roupa.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Quantidade)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Reserva.Tamanho)
                </td>

                <td>
                    @item.Reserva.Envio
                </td>

                <td>
                    <a asp-action="Chat" asp-controller="Accounts" asp-route-id="@item.Reserva.Id">
                        <img src="~/documentos/icons/chaticon.png" height="30" width="30" />
                        
                    </a>
                    @if (item.UnreadMessages > 0)
                    {
                        <strong class=" noUnderline" style="color:red;">@item.UnreadMessages</strong>

                    }
                </td>
                
            </tr>

        }

    </tbody>

</table>

Views/Reservas/Order.cshtml
@model IEnumerable<ShoraWebsite.Models.Reserva>


@if (ViewBag.statusMessages != null)
{
    <div class="alert alert-success alert-dismissible" role="alert" id="statusMessage">
        @foreach (var s in ViewBag.statusMessages)
        {
            <p>@s</p>
        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('statusMessage')"></button>
    </div>
}


@if (ViewBag.errorsMessages != null)
{
    <div class="alert alert-danger alert-dismissible " role="alert" id="errorMessage">
        @foreach (var s in ViewBag.errorsMessages)
        {
            <p>@s</p>

        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('errorMessage')"></button>
    </div>
}
<div class="container">
    <div class="row">
        <form asp-action="Listagem">
            <div class="input-group rounded">
                <input type="search" name="search" class="form-control rounded" placeholder="Pesquisa" aria-label="Search" aria-describedby="search-addon" />

                <button type="submit" class="btn btn-outline-dark">
                    <img src="/Documentos/Icons/searchIcon.png" height="30" width="30" />
                </button>

            </div>
        </form>
    </div>
    <div class="row">
        <h2> Lista de Reservas </h2>
    </div>
    <div class="row">

        <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                Ordenar
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li> <a class="nav-link text-dark" asp-action="Listagem"> Tudo </a></li>
                <li> <a class="nav-link text-dark" asp-route="ordered" asp-route-value="0">Não Vendido</a></li>
                <li><a class="nav-link text-dark" asp-route="ordered" asp-route-value="1"> Vendido</a></li>
            </ul>
        </div>

    </div>
</div>
</div>

<div class="container">

    <div class="row">
        <div class="col-sm">
            <partial name="Listing" model="@Model" />
        </div>


    </div>
</div>

Views/Reservas/Search.cshtml
@model IEnumerable<ShoraWebsite.Models.Reserva>


@if (ViewBag.statusMessages != null)
{
    <div class="alert alert-success alert-dismissible" role="alert" id="statusMessage">
        @foreach (var s in ViewBag.statusMessages)
        {
            <p>@s</p>
        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('statusMessage')"></button>
    </div>
}


@if (ViewBag.errorsMessages != null)
{
    <div class="alert alert-danger alert-dismissible " role="alert" id="errorMessage">
        @foreach (var s in ViewBag.errorsMessages)
        {
            <p>@s</p>

        }
        <button type="button" class="btn-close" onclick="closePopUpMessage('errorMessage')"></button>
    </div>
}

<h2> Lista de Reservas </h2>


<div class="container">
    <div class="row">
        <div class="col-sm">
            <partial name="Listing" model="@Model" />
        </div>


    </div>
</div>