Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ShoraWebsite.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace ShoraWebsite.Areas.Identity.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<IdentityUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

       
    }
}

Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoraWebsite.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ShoraWebsite.Models;
using ShoraWebsite.Data.Migrations;

namespace ShoraWebsite.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        public AccountsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        [Authorize(Roles = "Admin")]
        public IActionResult AdminPainel()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {

            var users = _userManager.Users;
            var model = new List<UsersRolesViewModel>();
            foreach (var user in users)
            {
                var roles = _userManager.GetRolesAsync(user).Result;
                model.Add(new UsersRolesViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    Role = roles.SingleOrDefault()
                });
            }
            return View(model);
        }


        [Authorize(Roles = "Admin,Cliente")]
        public IActionResult Chat(int? id)
        {


            if (!ReservaExiste(id))
            {
                return RedirectToAction("Index", "Home");
            }

            var reserva = _context.Reserva
                .Include(x => x.Roupa)
                .Include(x => x.Perfil)
                .Include(x => x.Perfil.User)
                .SingleOrDefault(x => x.Id == id);
            if (reserva.Perfil.User.UserName == User.Identity.Name || User.IsInRole("Admin"))
            {
                ViewData["MetodoId"] = new SelectList(ReservasController.GetMetodoDeEnvio(), "value", "metodo", reserva.Envio);
                ViewBag.Id = id;
                return View(reserva);
            }

            return RedirectToAction("Index", "Home");

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Editar(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var roles = _roleManager.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();

            var model = new UsersRolesViewModel
            {
                Id = user.Id,
                Email = user.Email,
                Role = (await _userManager.GetRolesAsync(user)).SingleOrDefault(),
                Roles = roles
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(string id, UsersRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var oldRole = model.Role;
            // Remove o user de todos os roles
            var result = await _userManager.RemoveFromRolesAsync(user, await _userManager.GetRolesAsync(user));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("Role", "Um erro ococrreu a dar update ao role do utilizador.");
                model.Role = oldRole;
                return View(model);
            }

            // Adicionar o role selecionado ao utilizador
            result = await _userManager.AddToRoleAsync(user, model.Role);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("Role", "Um erro ococrreu a dar update ao role do utilizador.");
                model.Role = oldRole;

                return View(model);
            }

            return RedirectToAction("Index");
        }


        public bool ReservaExiste(int? id)
        {
            if (id == null)
            {
                return false;
            }
            return _context.Reserva.Any(x => x.Id == id);
        }

    }
}

Controllers/ClothsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoraWebsite.Data;
using ShoraWebsite.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using Humanizer;
using Newtonsoft.Json.Linq;
using System.Collections;

namespace ShoraWebsite.Controllers
{
    public class ClothsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostEnvironment _he;
        private readonly UserManager<IdentityUser> _userManager;



        public ClothsController(ApplicationDbContext context, IHostEnvironment he, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _he = he;
            _userManager = userManager;
        }

        // GET: Cloths
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Listagem()
        {
            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;

            try
            {


                var stock = await _context.StockMaterial.Include(r => r.Roupa)
                    .OrderBy(s => s.Roupa.CategoriaId)
                    .ToArrayAsync();

                var roupas = await _context.Roupa.Include(r => r.Categoria).ToListAsync();

                foreach (var s in stock)
                {
                    foreach (var r in roupas)
                    {
                        if (s.RoupaId == r.Id)
                        {
                            r.Quantidade += s.Quantidade;
                        }
                    }
                }




                return View(roupas);

            }
            catch (Exception ex)
            {
                return Problem($"Houve um imprevisto\nErro:{ex}");
            }

        }

        //Get
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Detalhes(int? id)
        {
            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;

            if (id == null || _context.Roupa == null)
            {
                return NotFound();
            }

            var roupa = await _context.Roupa
                .Include(r => r.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);


            if (roupa == null)
            {
                return NotFound();
            }


            if (String.IsNullOrWhiteSpace(roupa.Foto))
            {
                ViewData["Fotos"] = null;
            }
            else
            {
                ViewData["Fotos"] = roupa.Foto.Split(";");
            }

            List<Stock> stock = new List<Stock>();
            if (_context.StockMaterial != null)
            {
                stock = await _context.StockMaterial.Where(s => s.RoupaId == roupa.Id).ToListAsync();

            }

            ViewBag.Stock = stock;

            return View(roupa);
        }

        //get
        public async Task<IActionResult> Material(int? id)
        {

            ViewBag.statusMessages = TempData.TryGetValue("statusMessages", out var statusMessages) ? statusMessages : null;
            ViewBag.errorsMessages = TempData.TryGetValue("errorsMessages", out var errorMessages) ? errorMessages : null;


            if (id == null || _context.Roupa == null)
            {
                return NotFound();
            }

            var roupa = await _context.Roupa
                .Include(r => r.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (roupa == null)
            {
                return NotFound();
            }


            if (!String.IsNullOrWhiteSpace(roupa.Foto))
            {
                ViewData["Fotos"] = roupa.Foto.Split(";");

            }
            else
            {
                ViewData["Fotos"] = null;
            }

            var stocks = await _context.StockMaterial.Where(s => s.RoupaId == roupa.Id)
                .ToListAsync();
            ViewData["Stock"] = stocks;

            foreach(var s in stocks)
            {
                roupa.Quantidade += s.Quantidade;
            }

            return View(roupa);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Cliente")]
        public async Task<IActionResult> Material([Bind("Id,Name,CategoriaId,Preco,Foto")] Roupa roupa, IFormCollection formData)
        {

            //verifico se o id passado é igual ao do form e vou buscar a roupa e verifico se a roupa existe na DB
            if (roupa.Id.ToString() != formData["roupaId"] || (roupa = await _context.Roupa.Include(r => r.Categoria).FirstOrDefaultAsync(r => r.Id == roupa.Id)) == null)
            {
                return Problem("Não foi encrontrada a roupa");
            }




            if (!TryGetUserPerfil(out int? perfilID))
            {
                return Problem("Não foi encontrado o utilizador");
            }


            if (!TryGetRoupaFromDatabase(roupa.Id, out roupa))
            {
                return Problem("Não foi encrontrada a roupa");

            }



            //Recebo os parametros do Form
            string[] quantArray = { formData["Quant_XS"], formData["Quant_S"], formData["Quant_M"], formData["Quant_L"], formData["Quant_XL"], formData["Quant_XXL"] };

            //Tamanhos existentes
            string[] sizes = { "XS", "S", "M", "L", "XL", "XXL" };

            //Lista de stock para depois atualizar na DB
            var stockList = new List<Stock>();
            //Crio uma lista de Reservas para depois adicionar a DB
            List<Reserva> reservaList = new List<Reserva>();

            //Listas de Mensagens de Erro e de Status
            List<string> errorMessages = new List<string>();
            List<string> statusMessages = new List<string>();

            //Array com as strings das fotos

            if (String.IsNullOrWhiteSpace(roupa.Foto))
            {
                ViewData["Fotos"] = null;
            }
            else
            {
                ViewData["Fotos"] = roupa.Foto.Split(";");
            }

            //Passo por todos os tamanhos recebidos e por seu Tamanho
            for (int i = 0; i < quantArray.Length; i++)
            {
                //Se for diferente de nulo vou processar
                if (!String.IsNullOrWhiteSpace(quantArray[i]))
                {

                    //Tentar fazer Parsing
                    try
                    {
                        if (int.TryParse(quantArray[i], out int quantidade) && quantidade > 0)
                        {
                            Stock stock;
                            if (TryGetStock(roupa.Id, sizes[i], out stock))
                            {
                                //Se por ventura o utilizador tentar comprar mais material que existe na DB
                                if (stock.Quantidade - quantidade >= 0)
                                {

                                    //Temos Stock para processar a reserva

                                    stock.Quantidade -= quantidade;
                                    //Verifico se acabou com o stock
                                    if (stock.Quantidade == 0)
                                    {
                                        _context.StockMaterial.Remove(stock);
                                    }
                                    else
                                    {
                                        stockList.Add(stock); //adiciono a lista de stock para ser alterado
                                    }

                                    //Adiciono a Reserva a DB
                                    reservaList.Add(new Reserva
                                    {
                                        Quantidade = quantidade,
                                        RoupaId = roupa.Id,
                                        Vendida = false,
                                        PerfilId = (int)perfilID,
                                        Tamanho = sizes[i]

                                    });
                                    //Adiciono a Status Message
                                    statusMessages.Add($"Foram reservados {quantidade} {roupa.Name} {sizes[i]}");

                                }
                                else
                                {
                                    errorMessages.Add($"Houve um imprevisto, não temos stock suficiente para a reserva submetida de {roupa.Name}-{sizes[i]}");
                                }
                            }
                        }
                        else
                        {
                            errorMessages.Add($"Houve erro com o Input de {sizes[i]} de {roupa.Name}, logo não foi possivel reservar este tamanho");
                        }
                    }
                    catch (Exception ex)
                    {

                        return Problem("Encontramos um problema :" + ex);
                    }
                }
            }

            var stockPage = await _context.StockMaterial.Where(s => s.RoupaId == roupa.Id).ToListAsync();

            ViewData["Stock"] = stockPage;




            if (errorMessages.Count != 0)
            {
                ViewBag.errorsMessages = errorMessages;
                TempData["errorsMessages"] = errorMessages;

            }
            else
            {
                ViewBag.errorsMessages = null;
            }

            if (statusMessages.Count != 0)

Views/Accounts/AdminPainel.cshtml
<div class="container mt-5">
    <h1 class="text-center display-2">Painel de Administrador</h1>

    <div class="row">
        <div class="col-6">
            
            <div class="list-group">
                <h2 class="">Configurações Gerais</h2>
                <a class="button-89" role="button" asp-controller="Categorias" asp-action="Listagem">Categorias</a>
               
                <h2 class="">Gestão de Material</h2>
                <a class="button-89" role="button" asp-controller="Cloths" asp-action="Listagem">Roupas</a>
                <a class="button-89" role="button" asp-controller="Reservas" asp-action="Listagem">Reservas</a>

                <h2 class="">Gestão do Website</h2>
                <a class="button-89 " role="button" asp-controller="Accounts" asp-action="Index">Contas</a>
                <a class="button-89" role="button" asp-controller="Home" asp-action="ControlIndex">Pagina Inicial</a>
            </div>

        </div>
        <div class="col-5">
            <img src="/Documentos/FotosWebSite/SHORA_FLAMES.png" style="max-height:500px;" />
        </div>

    </div>
</div>

Views/Accounts/Chat.cshtml
@model ShoraWebsite.Models.Reserva

<h4>Reserva de @Model.Perfil.FirstName @Model.Perfil.LastName</h4>
<hr />

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body chat-box" style="max-height: 400px; overflow-y: auto; min-height:400px;" id="messagesList">
                    <!--Mensagens-->
                </div>
                <div class="card-footer">
                    <div class="input-group">
                        <input type="text" class="form-control" id="messageInput" placeholder="Digite sua mensagem..." />
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button" id="sendButton">Enviar</button>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" id="reservaInput" value="@ViewBag.Id" />
            <input type="hidden" id="userInput" value="@User.Identity.Name" />
        </div>
        <div class="col">
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Roupa</th>
                        <td>@Html.DisplayFor(model => model.Roupa.Name)</td>
                    </tr>
                    <tr>
                        <th scope="row">Comprador</th>
                        <td>@Model.Perfil.FirstName @Model.Perfil.LastName</td>
                    </tr>
                    <tr>
                        <th scope="row">Quantidade</th>
                        <td>@Html.DisplayFor(model => model.Quantidade)</td>
                    </tr>
                    <tr>
                        <th scope="row">Tamanho</th>
                        <td>@Html.DisplayFor(model => model.Tamanho)</td>
                    </tr>
                    <tr>
                        <th scope="row">Numero</th>
                        <td>@Html.DisplayFor(model => model.Perfil.User.PhoneNumber)</td>
                    </tr>
                    <tr>
                        <th scope="row">Vendida</th>
                        <td>
                            @if (Model.Vendida)
                            {
                                <p>Sim</p>
                            }
                            else
                            {
                                <p>Não</p>
                            }
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Envio</th>
                        <td>@Html.DisplayFor(model => model.Envio)</td>
                    </tr>
                </tbody>
            </table>
           
                    <hr />
                
            @if (User.IsInRole("Admin"))
            {
                <div class="col-sm">
                    @await Html.PartialAsync("~/Views/Reservas/Editar.cshtml", Model)
                </div>
            }
        </div>
    </div>

   
</div>




<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/Chat.js"></script>

Views/Accounts/Editar.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore
@model ShoraWebsite.Models.UsersRolesViewModel

@{
    ViewData["Title"] = "Editar Conta";
}

<h1>Editar</h1>

<form asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" disabled />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Role"></label>
        <select asp-for="Role" asp-items="Model.Roles" class="form-control"></select>
    </div>
    <div class="mb-3">
        
        <button type="submit" class="botaoDanger nav-link">Guardar</button>
    </div>
</form>

<div class="mb-3">
    
    <a class="botao nav-link" asp-action="Index">Voltar a lista</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Accounts/Index.cshtml
@model List<UsersRolesViewModel>

@{
    ViewData["Title"] = "Lista Utilizadores";
}

<h1>Lista de Utilizadores</h1>


<table class="table">
    <thead>
        <tr>
            <th>
               Email
            </th>
            <th>
                Cargo
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>@item.Email</td>
                    <td>@item.Role</td>
                    
                    <td>
                    <a asp-action="Editar" class="botao nav-link" asp-controller="Accounts" asp-route-id="@item.Id">Editar</a>
                    </td>
                </tr>
        }
    </tbody>
</table>